### ISSUE TITLE
Incompatible with  God Module & possible others.

### ISSUE THREAD

**Issue by SGZ-Creations** [BanditTech/adjustable-quality#4]
Incompatible with https://mods.factorio.com/mod/god-module
please add some exceptions to allow for some modules not to be effected ?
 
```lua
    if effects.speed and effects.speed > 0 then
        if unlink then
            effects.quality = 0
        else
            if quality_mapping[effects.quality] then effects.quality = quality_mapping[effects.quality] end
        end
    end
```
By Honktown Factorio discord
<img width="707" height="156" alt="Image" src="https://github.com/user-attachments/assets/8ce187dd-9b79-4262-8e56-a9e1868336e0" />

**Comment by SGZ-Creations** [comment]
ty

**Comment by BanditTech** [comment]
I was busy with other things and had a moment to make the adjustment, but I didn't test it. I accidentally left a stray `end` operator at the end of the line 29. Should be resolved now.

**Comment by SGZ-Creations** [comment]
then it will stil crash as i removed the same end. Still crashing after trying to fixing that myself

then i was left with
`Failed to load mods: __adjustable-quality__/data-final-fixes.lua:26: attempt to compare nil with number`

**Comment by SGZ-Creations** [comment]
Thanks the mod loads & works as i hoped too.
